const PricingFeatures = {
	MESSAGE_CREDITS_GPT3_100: "100 Free GPT 3.5 Messages/month",
	MESSAGE_CREDITS_GPT3_2000: "2,000 GPT 3.5 Messages/month",
	MESSAGE_CREDITS_GPT3_5000: "5,000 GPT 3.5 Messages/month",
	MESSAGE_CREDITS_GPT3_10000: "10,000 GPT 3.5 Messages/month",
	MESSAGE_CREDITS_GPT4_500: "500 GPT-4 message credits/month",
	EMBED_UNLIMITED_WEBSITES: "Embed on Unlimited Websites",
	GPT35_OPTION: "Access to GPT-3.5",
	CHATBOT_1: "Create 1 Chatbots",
	CHATBOT_2: "Create 2 Chatbots",
	CHATBOT_5: "Create 5 Chatbots",
	CHATBOT_UNLIMITED: "Create Unlimited Chatbots",
	CHARACTERS_400K: "400,000 Characters/Chatbot",
	CHARACTERS_11M: "11,000,000 Characters/chatbot",
	GPT4_OPTION: "Access to GPT-4",
	SUPPORT_24_7: "24/7 Support",
	PRIORITY_SUPPORT: "Priority Support",
	FREE_TRIAL: "Free Trial Available",
};

export const PricingPlans = {
	FREE: {
		name: "Free",
		id: "free",
		features: [
			PricingFeatures.CHATBOT_1,
			PricingFeatures.CHARACTERS_400K,
			PricingFeatures.EMBED_UNLIMITED_WEBSITES,
			PricingFeatures.GPT35_OPTION,
			PricingFeatures.MESSAGE_CREDITS_GPT3_100,
		],
		buttonText: "Try Now !",
		monthlyPrice: "Free",
		yearlyPrice: "Free",
	},
	BASIC: {
		name: "Basic",
		id: "basic",
		features: [
			PricingFeatures.CHATBOT_1,
			PricingFeatures.CHARACTERS_400K,
			PricingFeatures.EMBED_UNLIMITED_WEBSITES,
			PricingFeatures.GPT35_OPTION,
			PricingFeatures.MESSAGE_CREDITS_GPT3_2000,
			PricingFeatures.FREE_TRIAL,
		],
		buttonText: "Start Free",
		monthlyPrice: "$29/month",
		yearlyPrice: "$299/year",
	},
	ESSENTIAL: {
		name: "Essential",
		id: "essential",
		features: [
			PricingFeatures.CHATBOT_2,
			PricingFeatures.CHARACTERS_400K,
			PricingFeatures.EMBED_UNLIMITED_WEBSITES,
			PricingFeatures.GPT35_OPTION,
			PricingFeatures.MESSAGE_CREDITS_GPT3_5000,
			PricingFeatures.SUPPORT_24_7,
		],
		buttonText: "Subscribe",
		monthlyPrice: "$49/month",
		yearlyPrice: "$499/year",
	},
	PRO: {
		name: "Pro",
		id: "pro",
		features: [
			PricingFeatures.CHATBOT_2,
			PricingFeatures.CHARACTERS_11M,
			PricingFeatures.EMBED_UNLIMITED_WEBSITES,
			PricingFeatures.GPT35_OPTION,
			PricingFeatures.MESSAGE_CREDITS_GPT3_10000,
			PricingFeatures.GPT4_OPTION,
			PricingFeatures.MESSAGE_CREDITS_GPT4_500,
			PricingFeatures.PRIORITY_SUPPORT,
		],
		buttonText: "Go Pro",
		monthlyPrice: "$99/month",
		yearlyPrice: "$999/year",
	},
};
