export const PrivateKeys = {
	// Live
	NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
		process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY_LIVE,
	// Testing
	// NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
	// 	process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY_TEST,
};
